// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Connection struct {
	ID        string  `bson:"id"`
	Username1 string  `bson:"username1"`
	User1     *User   `bson:"user1"`
	Username2 string  `bson:"username2"`
	User2     *User   `bson:"user2"`
	Debt      float64 `bson:"debt"`
	CreatedAt string  `bson:"createdAt"`
}

type ConnectionResult struct {
	Success    bool        `bson:"success"`
	Connection *Connection `bson:"connection"`
	Errors     []string    `bson:"errors"`
}

type InvoiceOrPayment struct {
	ID                string      `bson:"id"`
	CreatedByUsername string      `bson:"createdByUsername"`
	CreatedBy         *User       `bson:"createdBy"`
	ConnectionID      string      `bson:"connectionId"`
	Connection        *Connection `bson:"connection"`
	Amount            float64     `bson:"amount"`
	CreatedAt         string      `bson:"createdAt"`
}

type InvoiceOrPaymentInput struct {
	CreatedByUsername string  `bson:"createdByUsername"`
	ConnectionID      string  `bson:"connectionId"`
	Amount            float64 `bson:"amount"`
}

type InvoiceResult struct {
	Success bool              `bson:"success"`
	Invoice *InvoiceOrPayment `bson:"invoice"`
	Errors  []string          `bson:"errors"`
}

type PartialUser struct {
	ID            string        `bson:"id"`
	Username      string        `bson:"username"`
	DisplayName   string        `bson:"displayName"`
	ConnectionIds []string      `bson:"connectionIds"`
	Connections   []*Connection `bson:"connections"`
	CreatedAt     string        `bson:"createdAt"`
}

type PaymentResult struct {
	Success bool              `bson:"success"`
	Payment *InvoiceOrPayment `bson:"payment"`
	Errors  []string          `bson:"errors"`
}

type Result struct {
	Success bool     `bson:"success"`
	Errors  []string `bson:"errors"`
}

type UserAuthResult struct {
	Success bool     `bson:"success"`
	User    *User    `bson:"user"`
	Token   string   `bson:"token"`
	Errors  []string `bson:"errors"`
}

type UserConnection struct {
	ID              string  `bson:"id"`
	ContactUsername string  `bson:"contactUsername"`
	Contact         *User   `bson:"contact"`
	Debt            float64 `bson:"debt"`
	CreatedAt       string  `bson:"createdAt"`
}

type UserInput struct {
	Username string `bson:"username"`
	Password string `bson:"password"`
}

type UserResult struct {
	Success bool     `bson:"success"`
	User    *User    `bson:"user"`
	Errors  []string `bson:"errors"`
}

type UsersResult struct {
	Success bool     `bson:"success"`
	Users   []*User  `bson:"users"`
	Errors  []string `bson:"errors"`
}
