// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Connection struct {
	ID              string  `json:"id"`
	ContactUsername string  `json:"contact_username"`
	Contact         *User   `json:"contact"`
	Debt            float64 `json:"debt"`
	CreatedAt       string  `json:"created_at"`
}

type ConnectionResult struct {
	Success    bool        `json:"success"`
	Connection *Connection `json:"connection"`
	Errors     []string    `json:"errors"`
}

type InvoiceOrPayment struct {
	ID                string      `json:"id"`
	CreatedByUsername string      `json:"created_by_username"`
	CreatedBy         *User       `json:"created_by"`
	ConnectionID      string      `json:"connection_id"`
	Connection        *Connection `json:"connection"`
	Amount            float64     `json:"amount"`
	CreatedAt         string      `json:"created_at"`
}

type InvoiceOrPaymentInput struct {
	CreatedByUsername string  `json:"created_by_username"`
	ConnectionID      string  `json:"connection_id"`
	Amount            float64 `json:"amount"`
}

type InvoiceResult struct {
	Success bool              `json:"success"`
	Invoice *InvoiceOrPayment `json:"invoice"`
	Errors  []string          `json:"errors"`
}

type PaymentResult struct {
	Success bool              `json:"success"`
	Payment *InvoiceOrPayment `json:"payment"`
	Errors  []string          `json:"errors"`
}

type Result struct {
	Success bool     `json:"success"`
	Errors  []string `json:"errors"`
}

type User struct {
	ID            string              `json:"id"`
	Username      string              `json:"username"`
	Hash          string              `json:"hash"`
	DisplayName   string              `json:"display_name"`
	CreatedAt     string              `json:"created_at"`
	InvoiceIds    []string            `json:"invoice_ids"`
	Invoices      []*InvoiceOrPayment `json:"invoices"`
	PaymentIds    []string            `json:"payment_ids"`
	Payments      []*InvoiceOrPayment `json:"payments"`
	ConnectionIds []string            `json:"connection_ids"`
	Connections   []*Connection       `json:"connections"`
}

type UserAuthResult struct {
	Success bool     `json:"success"`
	User    *User    `json:"user"`
	Token   string   `json:"token"`
	Errors  []string `json:"errors"`
}

type UserInput struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type UserResult struct {
	Success bool     `json:"success"`
	User    *User    `json:"user"`
	Errors  []string `json:"errors"`
}

type UsersResult struct {
	Success bool     `json:"success"`
	Users   []*User  `json:"users"`
	Errors  []string `json:"errors"`
}
